apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: podinfo-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://github.com/stefanprodan/podinfo
      chart: podinfo
      targetRevision: 6.11.2
      helm:
        releaseName: podinfo
        valueFiles:
          - $values/gitops/charts/podinfo/values-dev.yaml
    - repoURL: https://github.com/UperPenta/infra-refresher.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: podinfo-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true